/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_canzhang_sample_manager_jni_JNITest */

#ifndef _Included_com_canzhang_sample_manager_jni_JNITest
#define _Included_com_canzhang_sample_manager_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_canzhang_sample_manager_jni_JNITest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_canzhang_sample_manager_jni_JNITest_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
